### ISSUE TITLE
无法查询到信息

### ISSUE THREAD

**Issue by L1ulee** [fofapro/fofa-java#8]
**描述错误**
使用示例的查询用户数据语句无法查询到数据
```java
public static void main(String[] args) throws Exception {
    // FOFA Pro email
    String email = "";
    // FOFA Pro key
    String key = "";
    FofaClient client = new FofaClient(email, key);
    System.out.println(client.getUser());
}
```

**步骤复现**
```java
package main.java;

import com.r4v3zn.fofa.core.client.FofaClient;

public class Fofa {

    public static void main(String[] args) throws Exception {
        // FOFA Pro email
        String email = "11******7@qq.com";
        // FOFA Pro key
        String key = "41******************************2";
        FofaClient client = new FofaClient(email, key);
        System.out.println(client.getUser());
    }

}
```
返回结果：
```
avax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
	at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(SSLSocketImpl.java:1709)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1508)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at com.r4v3zn.fofa.core.util.HttpUtils.doGet(HttpUtils.java:69)
	at com.r4v3zn.fofa.core.client.FofaClient.getUser(FofaClient.java:83)
	at main.java.Fofa.main(Fofa.java:15)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
	... 12 more
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asText()" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null
	at com.r4v3zn.fofa.core.client.FofaClient.getUser(FofaClient.java:89)
	at main.java.Fofa.main(Fofa.java:15)
```

**环境**
系统架构:Arm64
Java版本:
> openjdk 17.0.2 2022-01-18
> OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
> OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode)

**Comment by xxxxbxxxxx** [comment]
使用之前设置 BASE_URL.BASE_URL = "https://fofa.info"
